import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const _appleIconPalette = <Color>[
  Color(0xFF34C759),
  Color(0xFF007AFF),
  Color(0xFFFF9500),
  Color(0xFFFF3B30),
  Color(0xFFAF52DE),
  Color(0xFF5AC8FA),
  Color(0xFFFF2D55),
  Color(0xFF5856D6),
  Color(0xFFFFCC00),
  Color(0xFF30B0C7),
];

final _iconColorOverrides = <IconData, Color>{
  Icons.palette: Color(0xFFAF52DE),
  Icons.color_lens: Color(0xFFAF52DE),
  Icons.brightness_6: Color(0xFFFF9500),
  Icons.brightness_medium: Color(0xFFFF9500),
  Icons.text_fields: Color(0xFF007AFF),
  Icons.format_size: Color(0xFF007AFF),
  Icons.play_arrow: Color(0xFF34C759),
  Icons.shuffle: Color(0xFFAF52DE),
  Icons.volume_up: Color(0xFFFF3B30),
  Icons.notifications: Color(0xFFFF3B30),
  Icons.notifications_outlined: Color(0xFFFF3B30),
  Icons.wifi: Color(0xFF007AFF),
  Icons.lock: Color(0xFF8E8E93),
  Icons.lock_outline: Color(0xFF8E8E93),
  Icons.info_outline: Color(0xFF007AFF),
  Icons.help_outline: Color(0xFF5856D6),
  Icons.home: Color(0xFF007AFF),
  Icons.folder: Color(0xFF007AFF),
  Icons.movie: Color(0xFFFF3B30),
  Icons.music_note: Color(0xFFFF2D55),
  Icons.live_tv: Color(0xFFAF52DE),
  Icons.tv: Color(0xFFAF52DE),
  Icons.download: Color(0xFF34C759),
  Icons.favorite: Color(0xFFFF2D55),
  Icons.star: Color(0xFFFFCC00),
  Icons.category: Color(0xFFFF9500),
  Icons.tune: Color(0xFF8E8E93),
  Icons.subtitles: Color(0xFF5AC8FA),
  Icons.opacity: Color(0xFF5AC8FA),
  Icons.view_sidebar: Color(0xFF007AFF),
};

final _cupertinoForMaterial = <IconData, IconData>{
  Icons.settings: CupertinoIcons.settings,
  Icons.settings_outlined: CupertinoIcons.settings,
  Icons.person: CupertinoIcons.person,
  Icons.person_outline: CupertinoIcons.person,
  Icons.lock: CupertinoIcons.lock,
  Icons.lock_outline: CupertinoIcons.lock,
  Icons.palette: CupertinoIcons.paintbrush,
  Icons.color_lens: CupertinoIcons.paintbrush,
  Icons.text_fields: CupertinoIcons.textformat_size,
  Icons.format_size: CupertinoIcons.textformat_size,
  Icons.play_arrow: CupertinoIcons.play_arrow,
  Icons.pause: CupertinoIcons.pause,
  Icons.shuffle: CupertinoIcons.shuffle,
  Icons.volume_up: CupertinoIcons.speaker_3,
  Icons.wifi: CupertinoIcons.wifi,
  Icons.notifications: CupertinoIcons.bell,
  Icons.notifications_outlined: CupertinoIcons.bell,
  Icons.info_outline: CupertinoIcons.info,
  Icons.help_outline: CupertinoIcons.question_circle,
  Icons.home: CupertinoIcons.house,
  Icons.folder: CupertinoIcons.folder,
  Icons.movie: CupertinoIcons.film,
  Icons.music_note: CupertinoIcons.music_note,
  Icons.tv: CupertinoIcons.tv,
  Icons.live_tv: CupertinoIcons.tv,
  Icons.download: CupertinoIcons.cloud_download,
  Icons.delete: CupertinoIcons.trash,
  Icons.delete_outline: CupertinoIcons.trash,
  Icons.search: CupertinoIcons.search,
  Icons.favorite: CupertinoIcons.heart,
  Icons.favorite_border: CupertinoIcons.heart,
  Icons.star: CupertinoIcons.star,
  Icons.star_border: CupertinoIcons.star,
  Icons.visibility: CupertinoIcons.eye,
  Icons.visibility_off: CupertinoIcons.eye_slash,
  Icons.chevron_right: CupertinoIcons.chevron_forward,
  Icons.category: CupertinoIcons.square_grid_2x2,
  Icons.tune: CupertinoIcons.slider_horizontal_3,
  Icons.subtitles: CupertinoIcons.captions_bubble,
  Icons.calendar_today: CupertinoIcons.calendar,
  Icons.schedule: CupertinoIcons.clock,
  Icons.devices: CupertinoIcons.device_phone_portrait,
};

Color appleSettingsIconColor(IconData icon) =>
    _iconColorOverrides[icon] ??
    _appleIconPalette[icon.codePoint % _appleIconPalette.length];

IconData cupertinoGlyphFor(IconData material) =>
    _cupertinoForMaterial[material] ?? material;
